# Site
repository: ShpetimJanuzi.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Shpëtim Januzi
title: Student
email: shpetim.januzi@gmail.com
website: ShpetimJanuzi.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: shpetimjanuzi
github_username:  shpetimjanuzi
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: shpetimjanuzi
linkedin_username: shpetimjanuzi
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: shpetimjanuzi
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Shpëtim and I'm a student at Didact Bildungsgesellschaft mbH.  I also have small experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>Java, swift</mark> and <mark>Eating Pizza</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/shpetimjanuzi/Lena-iOS
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>Swift</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: BMW Group
        link: bmwgroup.com
        # link_text: boringcompany.com
        sub_title: Montage Mitarbeiter
        caption: November 2017 - October 2021
        quote: >
          Die Bayerische Motoren Werke Aktiengesellschaft ist ein börsennotierter Automobil- und Motorradhersteller mit Sitz in München, der auch als BMW Group auftritt. Die Produktpalette umfasst die Automobil- und Motorrad-Marke BMW, die Automarken Mini und Rolls-Royce sowie die BMW-Submarken BMW M und BMW i
        description: | # this will include new lines to allow paragraphs
          ein fleißiger und verantwortungsvoller Arbeiter in der Montage von Autoteilen seit 4 Jahren in Folge für die schönsten Autos
      - layout: left
        title: Oniks SHPK Lavazza
        link: oniks-ks.com
         # link_text: boringcompany.com
        sub_title: Verkaufsleiter
         caption: September 2015 - October 2017
         quote: >
         Exklusiver Vertriebspartner für den Kosovo des besten Kaffees Lavazza
        description: | # this will include new lines to allow paragraphs
         Kundenberater und Betreuung von Geschäftskunden, Erstellung von Mitarbeiterplänen und Kaffee-Qualitätskontrolle in den Bar/Restaurants
      - layout: left
         title: Oniks SHPK Lavazza
          link: oniks-ks.com
          # link_text: boringcompany.com
          sub_title: IT Administrator
          caption: Februar 2011 - Mai 2011
          quote: >
           RTV21 (ein Akronym für Radio Televizioni 21; Englisch: Radio and Television 21) ist ein Medienunternehmen mit Sitz in Pristina, Kosovo, zu dem ein Radiosender (gegründet 1998), ein Fernsehsender (gegründet 1999)
          description: | # this will include new lines to allow paragraphs
          IT Administrator und IPTV Übertragungsteuerung
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Didact Bildungsgesellschaft mbH
        caption: April 2022 - Present
        sub_title: Fachninformatiker Anwendungsentwicklung
        quote: >
          Unter Umschulung versteht man die Aus- bzw. Weiterbildung für eine andere als die vorher ausgeübte oder erlernte Tätigkeit. Kenntnisse und Erfahrungen aus der vorigen Tätigkeit erlauben oft eine Verkürzung der Ausbildung zum neuen Berufsbild gegenüber einem Anfänger.
        description: | # this will include new lines to allow paragraphs
          Bei Didact lerne ich erste Schritte der Softwareentwicklung und wir lernen hauptsächlich Java

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Reisen
      - Gaming
      - Filme

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: ShpetimJanuzi.github.io

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
